version: '3.8'
services:
  api:
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - ./logs:/usr/src/app/logs

  db:
    image: postgres
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  data: {}
